# SLURM

paths :   
    out_folder: "/my_data/Results/MISR_SRDiff_LCC_MaxViT_HR5_ConvFormer_SR4_CAF_ALL/results/"
    out_model_name: "misr-s2-aer-seg"

    train_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_TRAIN.csv
    val_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_VALID.csv
    test_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_TEST.csv
    global_mtd_folder: /my_data/FLAIR_HUB/GLOBAL_ALL_MTD/
    ckpt_model_path: 


tasks: 
    train: True
    train_tasks: 
        init_weights_only_from_ckpt: False
        resume_training_from_ckpt: False

    predict: True
    write_files: True
    georeferencing_output: True

    metrics_only: False

inputs:
    # Inputs
    num_classes: 19
    num_channels_aer: 5 
    num_channels_sat: 4 
    sr_patch_size: 64
    ref_date: '05-15'
    nbts: 12 # 1: 12 images, 2: 6 images, 3: 4 images, 4: 3 images, 6: 2 images
    sr_scale: 6.25 # 6.25 for 20 cm GSD to 1.6 m GSD, 10 for 20 cm GSD to 2 m GSD
    sat_reflectance_train: 2_000 
    sat_reflectance_infer: 2_000 

hyperparams:
    num_epochs: 150
    batch_size: 10
    seed: 2025
    learning_rate: 0.00005

    optimizer: adamw  # [sgd / adam / adamw]
    optim_weight_decay: 0.01
    optim_betas: [0.9, 0.999]

    scheduler: one_cycle_lr #  [one_cycle_lr / reduce_on_plateau / cycle_then_plateau]
    warmup_fraction: 0.2 # if using one_cycle_lr. [0-1]
    plateau_patience: 10 # if using cycle_then_plateau
    loss_weights_aer_sat: [0.7, 0.3]
    loss_aux_sat_weight: 1.0
    loss_main_sat_weight: 1.0

hardware:
    accelerator: 'gpu'
    num_nodes: 1
    gpus_per_node: 1
    strategy: 'auto' # ddp_find_unused_parameters_true if num_nodes > 1
    num_workers: 10


saving:   
    ckpt_save_also_last: True
    ckpt_weights_only: False
    ckpt_monitor: 'val_miou'
    ckpt_monitor_mode: 'max'
    ckpt_earlystopping_patience: 20
    cp_csv_and_conf_to_output: True
    enable_progress_bar: True
    progress_rate: 10
    ckpt_verbose: True
    verbose_config: False




