modalities: 

    inputs:
        AERIAL_RGBI       : True
        DEM_ELEV          : True
        SPOT_RGBI         : True
        SENTINEL2_TS      : True 
        
    inputs_channels: # starts at 1
        AERIAL_RGBI       : [1,2,3,4] 
        SPOT_RGBI         : [1,2,3,4]
        SENTINEL2_TS      : [1,2,3,6] # [1,2,3,4,5,6,7,8,9,10]

    aux_loss: 
        AERIAL_RGBI       : False
        DEM_ELEV          : False
        SPOT_RGBI         : False
        SENTINEL2_TS      : False

    aux_loss_weight: 1.5 

    modality_dropout: 
        AERIAL_RGBI       : 0
        DEM_ELEV          : 0
        SPOT_RGBI         : 0
        SENTINEL2_TS      : 0

    pre_processings: 
        filter_sentinel2: True 
        filter_sentinel2_max_cloud : 1 # [0-100]
        filter_sentinel2_max_snow : 1 # [0-100]
        filter_sentinel2_max_frac_cover : 0.05 # [0-1]
        temporal_average_sentinel2 : monthly  # [False / monthly / semi-monthly]
        temporal_diff: custom # [default / custom ] # custom: reference date is the SPOT image aquisition
        calc_elevation : True
        calc_elevation_stack_dsm : True 
        
        use_augmentation: False
        val_percent: 0.9
        
    normalization: 
        norm_type : custom   # [custom / scaling / without]

        AERIAL_RGBI_means : [105.66, 111.35, 102.18, 106.59]  
        AERIAL_RGBI_stds  : [52.23, 45.62, 44.30, 39.78]

        SPOT_RGBI_means : [433.26, 508.75, 467.77, 1137.03]
        SPOT_RGBI_stds  : [312.76, 284.61, 226.02, 543.11]

        DEM_ELEV_means : [311.06, 311.06] # use same for both DSM/DTM to allow keeping differences of elevation
        DEM_ELEV_stds  : [537.55, 537.55] # use same for both DSM/DTM to allow keeping differences of elevation
