labels: 
  - AERIAL_LABEL-COSIA
#   - ALL_LABEL-LPIS

labels_configs:
    AERIAL_LABEL-COSIA:
        task_weight: 1
        value_name:
            0  : 'building'
            1  : 'greenhouse'
            2  : 'swimming_pool'
            3  : 'impervious surface'
            4  : 'pervious surface'
            5  : 'bare soil'
            6  : 'water'
            7  : 'snow'
            8  : 'herbaceous vegetation'
            9  : 'agricultural land'
            10 : 'plowed land'
            11 : 'vineyard'
            12 : 'deciduous'
            13 : 'coniferous'
            14 : 'brushwood'
            15 : 'clear cut'
            16 : 'ligneous'
            17 : 'mixed'
            18 : 'undefined'
        value_weights: 
            default: 1
            default_exceptions:
                15: 0
                16: 0
                17: 0
                18: 0
            per_modality_exceptions:
                AERIAL_RGBI: 
                SENTINEL2_TS: 

    ALL_LABEL-LPIS:
        task_weight: 1
        
        value_name:
            0  : 'grasses'   
            1  : 'wheat'
            2  : 'barley'
            3  : 'maize'
            4  : 'other cereals'
            5  : 'rice'
            6  : 'flax/hemp/tobacco'
            7  : 'sunflower'
            8  : 'rapeseed'
            9  : 'other oilseed crops'
            10 : 'soy'
            11 : 'other protein crops'
            12 : 'fodder legumes'
            13 : 'beetroots'
            14 : 'potatoes'
            15 : 'other arable crops'
            16 : 'vineyard'
            17 : 'olive groves'
            18 : 'fruits orchards'
            19 : 'nut orchards'
            20 : 'other permanent crops'
            21 : 'mixed crops'
            22 : 'background'

        value_weights: 
            default: 1
            default_exceptions:
            per_modality_exceptions:
                SENTINEL2_TS: 

    label_channel_nomenclature: 1   