base_config:
  - ../sr_base.yaml
  - ../df2k4x.yaml
trainer_cls: tasks.rrdb_ltae.RRDBLtae
# model
hidden_size: 32
lr: 0.0002
num_block: 8

# train and eval
max_updates: 400000
batch_size: 2
eval_batch_size: 1
test_batch_size: 1
val_check_interval: 50000
save_ckpt_interval: 40000
train_diffsr: false
max_s2_images: 8
